### ISSUE TITLE
Bug: CIF spanish starting with U does not validate

### ISSUE THREAD

**Issue by Vargax01** [django/django-localflavor#464] opened 2021-11-11 08:43 UTC
Hello,
django-localflavor ES does not validate the cif that begin with U. I have been analyzing the code and I have seen that the U is not within the list of values ​​of the cif.

`self.cif_types = 'ABCDEFGHJKLMNPQRSVW'`

The cif that begin with U are totally valid (https://es.wikipedia.org/wiki/C%C3%B3digo_de_identificaci%C3%B3n_fiscal)

Could you tell me what to do to fix this.

Thanks greetings

**Comment by benkonrath** [comment] 2021-11-12 11:05
Hi, Thanks for the bug report. The best thing to do is submit a PR with the fix and passing test demonstrates that the issue is fixed. Thanks.

**Comment by sandeepN06** [comment] 2021-11-15 10:45
Hey @Vargax01 you could fork it and clone this repo in your pc and redirect to ES localflavour and you could alter the cif_types and run the tox if all tests get passed send a PR. If you face any difficulties just put a message

**Comment by Vargax01** [comment] 2021-11-16 08:22
Hi,
Yes I solve the problem, I edit the code in the forms.py file and change the line to this line: 
`self.cif_types = 'ABCDEFGHJKLMNPQRSUVW'`
And everything works perfectly.
I hope you can implement the updated cif letters in future versions

Thanks greetings

**Comment by sandeepN06** [comment] 2021-11-16 08:28
> Hi,
> Yes I solve the problem, I edit the code in the forms.py file and change the line to this line: 
> `self.cif_types = 'ABCDEFGHJKLMNPQRSUVW'`
> And everything works perfectly.
> I hope you can implement the updated cif letters in future versions
> 
> Thanks greetings

You need to create a PR to get your code merged

**Comment by benkonrath** [comment] 2022-05-06 07:51
Fixed in #469

**Closed by benkonrath** 2022-05-06 07:51 UTC
